fix(import): allow passing empty URLs
ts-factory/bublik-ui pull request #14
Opened 2024-01-12 18:49 UTC by okt-limonikas

2024-01-12 21:22 UTC, okt-kostik commented on libs/bublik/features/run-import/src/lib/import-run-form/__snapshots__/import-run-form-result-list.component.spec.tsx.snap
> -                href="https://www.youtube.com/watch?v=1"
Irrelevant change?

2024-01-12 21:23 UTC, okt-kostik requested changes
This looks like 2 commits:

 - actual fix you describe
 - fixes for cool youtube refs etc.

2024-01-15 04:08 UTC, okt-limonikas commented on libs/bublik/features/run-import/src/lib/import-run-form/__snapshots__/import-run-form-result-list.component.spec.tsx.snap
> -                href="https://www.youtube.com/watch?v=1"
Should be fixed now

2024-01-16 16:07 UTC, okt-kostik approved these changes

2024-01-17 15:42 UTC, merged